"""
Windows-only local dev fixup for a specific, intermittent symptom: some
Windows machines' Application Control policy blocks grpcio's compiled
`cygrpc` extension outright, and chromadb unconditionally imports an
OTLP/gRPC telemetry exporter at package init (via chromadb.auth.token_authn)
even though local PersistentClient usage never triggers OTLP export. See
CHANGES.md, "local-only stub for opentelemetry-exporter-otlp-proto-grpc"
for the full diagnosis.

This does NOT assume the block is always present — it was observed once,
then did not reproduce on a later run on the same machine (Windows
Application Control / Smart App Control decisions can apparently change
over time, e.g. after reputation evaluation). So this script *probes* the
actual symptom (`import chromadb` failing with this specific error) and
only strips/stubs grpcio if that symptom is currently real — it never
removes a working grpcio installation on a guess.

Idempotent — safe to run any number of times, including when nothing needs
fixing. Run it once after any `pip install -r backend/requirements.txt` on
a Windows dev machine:

    .venv\\Scripts\\python.exe scripts\\dev_setup_windows.py

This is a local dev-only fix. backend/requirements.txt is untouched —
Render's Linux deploy target installs grpcio normally and needs no stub.
"""
import importlib.metadata
import platform
import subprocess
import sys
import sysconfig
from pathlib import Path

PACKAGES_TO_STRIP = ["opentelemetry-exporter-otlp-proto-grpc", "grpcio"]

BLOCK_SYMPTOM_MARKERS = ("cygrpc", "application control policy")

STUB_CONTENT = '''"""
Local stub replacing opentelemetry-exporter-otlp-proto-grpc.

grpcio's compiled extension was blocked by this machine's Windows
Application Control policy at the time this was applied. Chromadb imports
OTLPSpanExporter unconditionally at package init even though local
PersistentClient usage never triggers OTLP/gRPC telemetry export, so this
stub exists purely to satisfy that import. See CHANGES.md. Not committed
to the repo; Render (Linux) deployment is unaffected and can use the real
package.

Regenerated by scripts/dev_setup_windows.py — do not hand-edit; re-run
that script instead if this file is ever missing or stale.
"""
from opentelemetry.sdk.trace.export import SpanExporter, SpanExportResult


class OTLPSpanExporter(SpanExporter):
    def __init__(self, *args, **kwargs):
        pass

    def export(self, spans):
        return SpanExportResult.SUCCESS

    def shutdown(self):
        pass
'''


def is_installed(package_name: str) -> bool:
    try:
        importlib.metadata.distribution(package_name)
        return True
    except importlib.metadata.PackageNotFoundError:
        return False


def try_import(module_name: str) -> tuple[bool, str]:
    """Imports in a fresh subprocess so we see the real, current state — not this
    process's already-cached (or already-broken) import state."""
    result = subprocess.run(
        [sys.executable, "-c", f"import {module_name}"],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0, result.stderr


def looks_like_the_known_block(stderr: str) -> bool:
    lowered = stderr.lower()
    return all(marker in lowered for marker in BLOCK_SYMPTOM_MARKERS) or (
        "cygrpc" in lowered and "dll load failed" in lowered
    )


def write_stub() -> Path:
    site_packages = Path(sysconfig.get_paths()["purelib"])
    stub_dir = site_packages / "opentelemetry" / "exporter" / "otlp" / "proto" / "grpc"
    trace_exporter_dir = stub_dir / "trace_exporter"
    trace_exporter_dir.mkdir(parents=True, exist_ok=True)

    (stub_dir / "__init__.py").write_text("", encoding="utf-8")
    stub_file = trace_exporter_dir / "__init__.py"
    stub_file.write_text(STUB_CONTENT, encoding="utf-8")
    return stub_file


def main() -> None:
    if platform.system() != "Windows":
        print("Not on Windows — this fixup is not needed here. Skipping.")
        return

    ok, _ = try_import("chromadb")
    if ok:
        print("chromadb already imports cleanly — no fix needed, nothing changed.")
        return

    _, stderr = try_import("chromadb")
    if not looks_like_the_known_block(stderr):
        print("chromadb import is failing, but NOT with the known grpcio/Application")
        print("Control symptom this script fixes. Not touching packages — here's the")
        print("real error so it can be diagnosed properly:\n")
        print(stderr)
        sys.exit(1)

    print("Reproduced the known grpcio Application Control block. Applying the fix.")
    installed = [pkg for pkg in PACKAGES_TO_STRIP if is_installed(pkg)]
    if installed:
        print(f"Stripping blocked packages from this venv: {', '.join(installed)}")
        subprocess.check_call([sys.executable, "-m", "pip", "uninstall", "-y", *installed])

    stub_file = write_stub()
    print(f"Wrote no-op OTLPSpanExporter stub at {stub_file}")

    ok, stderr = try_import("chromadb")
    if not ok:
        print("WARNING: chromadb import still fails after applying the stub:\n")
        print(stderr)
        sys.exit(1)
    print("Verified: chromadb now imports cleanly.")


if __name__ == "__main__":
    main()
